version: "3"
services:
  job-api:
    build: .
    command: ["./cli","serve"]
    ports:
      - "3000:3000"
    environment:
      SQL_USER: postgres
      SQL_PASSWORD: 123456
      SQL_NAME: postgres
      SQL_ADDRESS: postgres:5432
      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD: mypassword
      HTTP_PORT: 3000
    depends_on:
      - postgres
      - redis
  job-worker:
    build: .
    command: [ "./cli","worker"]
    environment:
      SQL_USER: postgres
      SQL_PASSWORD: 123456
      SQL_NAME: postgres
      SQL_ADDRESS: postgres:5432
      REDIS_ADDRESS: redis:6379
      JOB_PREFETCH: 10
      JOB_TIMEOUT: 30
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:12.8-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432
  redis:
    image: redis:5.0.13-alpine3.14
    restart: unless-stopped
    ports:
      - 6379
