version: "3"
services:
  job-api:
    build: .
    command: ["./cli","serve"]
    restart: always
    ports:
      - "3000:3000"
    environment:
      SQL_USER: postgres
      SQL_PASSWORD: 123456
      SQL_NAME: postgres
      SQL_ADDRESS: postgres:5432
      REDIS_ADDRESS: redis:6379
      HTTP_PORT: 3000
    depends_on:
      - postgres
      - redis
  job-worker:
    build: .
    command: [ "./cli","worker"]
    restart: always
    environment:
      SQL_USER: postgres
      SQL_PASSWORD: 123456
      SQL_NAME: postgres
      SQL_ADDRESS: postgres:5432
      REDIS_ADDRESS: redis:6379
      REDIS_PREFETCH: 1
      JOB_TIMEOUT: 10
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:12.8-alpine
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432
  redis:
    image: redis:5.0.13-alpine3.14
    ports:
      - 6379
volumes:
  database-data: